language: node_js

branches:
  only:
    - master

sudo: false

cache:
  npm: true
  directories:
    - node_modules
    
node_js:
  - node

install:
  - npm install

script:
  - npm run test:prod && npm run build

after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
